### ISSUE TITLE
Is the model structure as same as original?

### ISSUE THREAD

**Issue by murdockhou** [signatrix/regnet#1]
Thanks for your work. Is the model structure as same as original?

**Comment by vietnh1009** [comment]
Yes, you could see the comparison table we wrote in readme. Additionally, before you run training script, you could uncomment lines 27-30 to see the detail parameters (or you could run debugging to see it). It is compatible to what stated in the paper, with some minor difference.
Thanks,

**Comment by murdockhou** [comment]
Thanks. The facebook also provide their official regnet code but was too hard to read. I'll used your model structure for mine experiment. Waiting for your pre-trained model.
