### ISSUE TITLE
Why my Acc@5 always shown 100?

### ISSUE THREAD

**Issue by morris0824** [signatrix/regnet#3]
I followed the README to create data folder.
data
├── train
│   ├── n0
│   └── n1
│   └── n2
│   └── n3
│   └── n4
│── val
│   ├── n0
│   └── n1
│   └── n2
│   └── n3
│   └── n4

I modified the NUM_CLASSES = 5 at src/config.py.
And all config are default (RegnetY 200MF).

**Comment by vietnh1009** [comment]
Hi,
Acc@5 is the accuracy for the 5 predicted classes with highest probability. When you set NUM_CLASSES to 5, it mean that your dataset only has 5 classes, so these 5 classes will always have highest probability => acc@5 is always 100%.
Acc@5 is only meaningful if your dataset has more than 5 classes
Here is one explanation for these term if you are still not clear: https://www.quora.com/What-does-the-terms-Top-1-and-Top-5-mean-in-the-context-of-Machine-Learning-research-papers-when-report-empirical-results

**Comment by morris0824** [comment]
@uvipen Thanks for your reply quickly. 
I thought that will follwed the NUM_CLASSES setting. If  my prediction classes less than 5, I need to modify LINE 147 & 193 at train.py. Am I correct?

**Comment by vietnh1009** [comment]
Yes, exactly
